-- event-flyers Storage bucket + RLS for organizer event flyer images.
--
-- Backing decision: docs/adr/0016-supabase-storage-for-event-images.md
-- (the Firebase Storage -> Supabase Storage move). Flyers are public marketing
-- images shown on public event pages, so the bucket is PUBLIC: free CDN caching
-- + image transforms, no signed-URL round-trips. Events.imageUrl stores the
-- object PATH (not a URL), so the serving host stays swappable later.
--
-- storage.buckets / storage.objects are Supabase-managed (not in the Prisma
-- schema), so this migration is hand-written rather than generated by
-- `yarn db:new` (which only diffs schema.prisma). Idempotent so it is safe on
-- prod (which may already have the bucket) and reproducible on every preview
-- branch built from migrations.

-- 1. The bucket. The 10 MB cap and image-only mime allowlist mirror the client
--    guard in apps/web/.../EventImageUpload.tsx, enforced server-side here too.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'event-flyers',
  'event-flyers',
  true,
  10485760, -- 10 MiB
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- 2. RLS on storage.objects, every policy scoped to bucket_id = 'event-flyers'.
--    Read is public (anyone can view a flyer); writes are limited to signed-in
--    users (ADR 0016: direct client upload governed by RLS). Policies are
--    dropped-then-created so re-running the migration is a no-op.
--    Note: RLS on storage.objects is enabled by Supabase by default.

drop policy if exists "event-flyers public read" on storage.objects;
create policy "event-flyers public read"
  on storage.objects for select
  to public
  using (bucket_id = 'event-flyers');

drop policy if exists "event-flyers authenticated insert" on storage.objects;
create policy "event-flyers authenticated insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'event-flyers');

drop policy if exists "event-flyers authenticated update" on storage.objects;
create policy "event-flyers authenticated update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'event-flyers')
  with check (bucket_id = 'event-flyers');

drop policy if exists "event-flyers authenticated delete" on storage.objects;
create policy "event-flyers authenticated delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'event-flyers');
